-- =============================================================================
-- Libra — rolul de administrator si ce poate vedea
--
-- Tabela public.user_roles exista deja (creata din consola). Aici e intarita si
-- primeste politicile care ii lipseau, apoi se deschide accesul
-- administratorilor la cazurile de verificare a identitatii si la pozele lor.
--
-- Doua lucruri merg impreuna si nu se despart:
--   1. dreptul de a vedea datele altcuiva;
--   2. urma ca l-ai folosit (public.acces_administrator).
-- Un drept de citire fara urma nu se poate verifica ulterior, iar aici vorbim
-- de buletinul si fata unor oameni.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. user_roles: constrangerile care lipseau
-- -----------------------------------------------------------------------------
create table if not exists public.user_roles (
  id      bigint generated by default as identity primary key,
  user_id uuid,
  role    text default ''
);

-- Un rand fara utilizator sau fara rol nu inseamna nimic; il stergem inainte
-- sa punem NOT NULL, altfel migrarea cade pe date vechi.
delete from public.user_roles where user_id is null or coalesce(btrim(role), '') = '';

alter table public.user_roles alter column user_id set not null;
alter table public.user_roles alter column role set not null;
alter table public.user_roles alter column role drop default;

-- Fara asta, acelasi om putea aparea de mai multe ori cu acelasi rol, iar
-- verificarile ar fi depins de care rand vine primul.
create unique index if not exists user_roles_user_rol_uk
  on public.user_roles (user_id, role);

alter table public.user_roles drop constraint if exists user_roles_role_check;
alter table public.user_roles
  add constraint user_roles_role_check check (role in ('user', 'admin'));

comment on table public.user_roles is
  'Rolurile utilizatorilor. Se scrie numai din consola sau cu service_role; niciodata din aplicatie.';

-- -----------------------------------------------------------------------------
-- 2. RLS pe rolurile insele
--
-- Fara politica de insert/update: daca aplicatia ar putea scrie aici, oricine
-- si-ar putea acorda singur rolul de admin cu o singura cerere.
-- -----------------------------------------------------------------------------
alter table public.user_roles enable row level security;

drop policy if exists "rolul propriu: select" on public.user_roles;
create policy "rolul propriu: select"
  on public.user_roles
  for select
  to authenticated
  using (user_id = (select auth.uid()));

grant select on public.user_roles to authenticated;

-- -----------------------------------------------------------------------------
-- 3. Cine e administrator
--
-- SECURITY DEFINER, si nu un subselect direct in politica: o politica ce ar
-- citi din user_roles ar declansa din nou RLS pe aceeasi tabela. Functia
-- ruleaza cu drepturile proprietarului, vede randul fara politici, si bucla
-- se rupe.
-- -----------------------------------------------------------------------------
create or replace function public.este_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $functie$
  select exists (
    select 1 from public.user_roles r
    where r.user_id = (select auth.uid()) and r.role = 'admin'
  );
$functie$;

revoke all on function public.este_admin() from public;
grant execute on function public.este_admin() to authenticated;

-- -----------------------------------------------------------------------------
-- 4. Ce vede un administrator
--
-- Politicile proprii ale utilizatorului raman neatinse; se adauga cate una
-- separata pentru admini, ca sa se vada in baza de date ca sunt doua drepturi
-- diferite, nu unul largit.
-- -----------------------------------------------------------------------------
drop policy if exists "admin: vede toate verificarile" on public.identity_verifications;
create policy "admin: vede toate verificarile"
  on public.identity_verifications
  for select
  to authenticated
  using (public.este_admin());

-- Update-ul e ingustat la coloanele deciziei prin trigger-ul de la punctul 5:
-- politica singura n-ar impiedica un admin sa rescrie scorul sau calea pozei.
drop policy if exists "admin: decide asupra verificarilor" on public.identity_verifications;
create policy "admin: decide asupra verificarilor"
  on public.identity_verifications
  for update
  to authenticated
  using (public.este_admin())
  with check (public.este_admin());

drop policy if exists "admin: vede profilurile" on public.profiles;
create policy "admin: vede profilurile"
  on public.profiles
  for select
  to authenticated
  using (public.este_admin());

-- -----------------------------------------------------------------------------
-- 5. Ce poate schimba un administrator intr-un caz
--
-- Doar decizia: status, reviewed_by, reviewed_at, notes. Dovezile pe care se
-- ia decizia — poze, CNP citit, scor, prag — raman cum le-a scris serviciul.
-- Altfel un raport de revizuire nu ar mai putea fi verificat de nimeni.
-- -----------------------------------------------------------------------------
create or replace function public.identity_verifications_protejeaza_dovezile()
returns trigger
language plpgsql
set search_path = ''
as $functie$
begin
  new.id                 := old.id;
  new.id_user            := old.id_user;
  new.buletin_image_path := old.buletin_image_path;
  new.selfie_image_path  := old.selfie_image_path;
  new.extracted_cnp      := old.extracted_cnp;
  new.similarity_score   := old.similarity_score;
  new.threshold_folosit  := old.threshold_folosit;
  new.creat_la           := old.creat_la;

  return new;
end;
$functie$;

drop trigger if exists identity_verifications_before_update on public.identity_verifications;
create trigger identity_verifications_before_update
  before update on public.identity_verifications
  for each row
  execute function public.identity_verifications_protejeaza_dovezile();

-- Decizia manuala trebuie sa se reflecte in profil, la fel ca cea automata.
-- Trigger-ul din 0004 prinde doar INSERT.
create or replace function public.sync_verification_status_update()
returns trigger
language plpgsql
security definer
set search_path = ''
as $functie$
begin
  if new.status is distinct from old.status then
    update public.profiles
       set verification_status = new.status,
           modificat_la = now()
     where id = new.id_user;
  end if;

  return new;
end;
$functie$;

drop trigger if exists identity_verifications_after_update on public.identity_verifications;
create trigger identity_verifications_after_update
  after update on public.identity_verifications
  for each row
  execute function public.sync_verification_status_update();

grant update on public.identity_verifications to authenticated;

-- -----------------------------------------------------------------------------
-- 6. Pozele
--
-- Bucket-urile raman private. Administratorul primeste drept de citire, ca sa
-- se poata genera un URL semnat cu durata scurta; nimic nu devine public.
-- -----------------------------------------------------------------------------
drop policy if exists "buletine: adminul vede toate pozele" on storage.objects;
create policy "buletine: adminul vede toate pozele"
  on storage.objects for select to authenticated
  using (bucket_id = 'buletine' and public.este_admin());

drop policy if exists "selfie: adminul vede toate pozele" on storage.objects;
create policy "selfie: adminul vede toate pozele"
  on storage.objects for select to authenticated
  using (bucket_id = 'selfie-uri' and public.este_admin());

-- -----------------------------------------------------------------------------
-- 7. Urma
-- -----------------------------------------------------------------------------
create table if not exists public.acces_administrator (
  id               uuid primary key default gen_random_uuid(),
  id_administrator uuid not null references public.profiles (id) on delete cascade,
  id_utilizator    uuid references public.profiles (id) on delete set null,
  actiune          text not null,
  detalii          text,
  creat_la         timestamptz not null default now(),

  constraint acces_actiune_check check (actiune in (
    'lista_alerte', 'raport_pdf', 'raport_csv',
    'lista_verificari', 'vede_verificare', 'decide_verificare'
  ))
);

comment on table public.acces_administrator is
  'Cine s-a uitat la datele cui, si cand. Se adauga, nu se modifica si nu se sterge.';

create index if not exists acces_administrator_idx
  on public.acces_administrator (id_administrator, creat_la desc);
create index if not exists acces_utilizator_idx
  on public.acces_administrator (id_utilizator, creat_la desc);

alter table public.acces_administrator enable row level security;

-- Un administrator isi vede propria urma. Nu si pe a colegilor: cine verifica
-- verificatorii se uita in baza de date, nu prin aplicatie.
drop policy if exists "administrator: isi vede urma" on public.acces_administrator;
create policy "administrator: isi vede urma"
  on public.acces_administrator
  for select
  to authenticated
  using (id_administrator = (select auth.uid()) and public.este_admin());

-- Fara update si fara delete: o urma care se poate rescrie nu mai e o urma.
drop policy if exists "administrator: isi scrie urma" on public.acces_administrator;
create policy "administrator: isi scrie urma"
  on public.acces_administrator
  for insert
  to authenticated
  with check (id_administrator = (select auth.uid()) and public.este_admin());

grant select, insert on public.acces_administrator to authenticated;

-- -----------------------------------------------------------------------------
-- 8. Cum faci primul administrator
--
--   insert into public.user_roles (user_id, role)
--   select id, 'admin' from auth.users where email = 'adresa@exemplu.ro'
--   on conflict (user_id, role) do nothing;
-- -----------------------------------------------------------------------------
