-- =============================================================================
-- Libra — rolul de administrator si ce poate vedea
--
-- Migrarea e ADITIVA: adauga politici, functii, un trigger si o tabela noua.
-- Nu sterge randuri, nu schimba forma vreunei tabele existente si nu atinge
-- datele nimanui. Se poate rula de mai multe ori fara alt efect.
--
-- Motivul e practic: SQL Editor-ul din Supabase nu ruleaza scriptul intr-o
-- tranzactie, deci o instructiune care cade la mijloc lasa baza pe jumatate
-- migrata. Intr-o baza comuna, in care lucreaza mai multi oameni, o migrare
-- care sterge ceva nu are cum sa fie sigura.
--
-- Tabela public.user_roles exista deja, creata din consola. Aplicatia doar
-- CITESTE din ea ("are omul asta un rand cu role = 'admin'?"), deci nu are
-- nevoie sa ii schimbe forma. Constrangerile care i-ar prinde bine sunt la
-- final, comentate, ca sa fie rulate de un om care se uita intai la date.
--
-- Doua lucruri merg impreuna si nu se despart:
--   1. dreptul de a vedea datele altcuiva;
--   2. urma ca l-ai folosit (public.acces_administrator).
-- Un drept de citire fara urma nu se poate verifica ulterior, iar aici vorbim
-- de buletinul si fata unor oameni.
-- =============================================================================

-- Renumerotare: fisierul a venit de pe branch-ul panoului de administrare cu
-- numarul 0005, ocupat intre timp pe main. Continutul e neschimbat, in afara de
-- punctul 3 (vezi acolo).
--
-- Ordine, daca cineva ruleaza vreodata istoricul de la zero: punctul 1 de mai jos
-- (tabela user_roles) trebuie sa existe INAINTE de 0009, fiindca functia
-- public.este_administrator() creata acolo o citeste, iar Postgres verifica
-- corpul unei functii `language sql` la creare. In proiectul real ordinea n-a
-- fost o problema — user_roles exista dinaintea tuturor migrarilor, creata din
-- consola. Vezi REGULI.md #3: istoricul din repo nu e o secventa rulabila de la
-- zero, ci evidenta a ce s-a aplicat.

-- -----------------------------------------------------------------------------
-- 1. Plasa de siguranta, daca tabela lipseste
--
-- Aceeasi forma cu cea creata din consola. Daca exista deja, nu se schimba
-- nimic — inclusiv default-ul si coloanele care accepta null raman cum sunt.
-- -----------------------------------------------------------------------------
create table if not exists public.user_roles (
  id      bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on update cascade on delete cascade,
  role    text default ''
);

comment on table public.user_roles is
  'Rolurile utilizatorilor. Se scrie din consola sau cu service_role; niciodata din aplicatie.';

-- -----------------------------------------------------------------------------
-- 2. RLS pe rolurile insele
--
-- Fara politica de insert/update: daca aplicatia ar putea scrie aici, oricine
-- si-ar putea acorda singur rolul de admin cu o singura cerere.
-- -----------------------------------------------------------------------------
alter table public.user_roles enable row level security;

drop policy if exists "rolul propriu: select" on public.user_roles;
create policy "rolul propriu: select"
  on public.user_roles
  for select
  to authenticated
  using (user_id = (select auth.uid()));

grant select on public.user_roles to authenticated;

-- -----------------------------------------------------------------------------
-- 3. Cine e administrator
--
-- Functia nu se mai defineste aici. public.este_administrator() exista din 0009
-- si a fost corectata in 0011: citeste tot din public.user_roles si accepta atat
-- 'admin' (valoarea randurilor reale, puse din consola) cat si 'administrator'.
--
-- Migrarea asta venea de pe un branch paralel cu a doua functie, cu alt nume dar
-- acelasi efect. Doua functii care raspund la aceeasi intrebare se
-- desincronizeaza la prima schimbare facuta doar in una, asa ca a ramas una
-- singura (REGULI.md #2). Peste tot mai jos se cheama public.este_administrator().
--
-- E SECURITY DEFINER, si nu un subselect direct in politica: o politica ce ar
-- citi din user_roles ar declansa din nou RLS pe aceeasi tabela. Functia ruleaza
-- cu drepturile proprietarului, vede randul fara politici, si bucla se rupe.
-- -----------------------------------------------------------------------------

-- -----------------------------------------------------------------------------
-- 4. Ce vede un administrator
--
-- Politicile proprii ale utilizatorului raman neatinse; se adauga cate una
-- separata pentru admini, ca sa se vada in baza de date ca sunt doua drepturi
-- diferite, nu unul largit. Politicile se aduna cu SAU, deci nimeni nu pierde
-- accesul pe care il avea.
-- -----------------------------------------------------------------------------
drop policy if exists "admin: vede toate verificarile" on public.identity_verifications;
create policy "admin: vede toate verificarile"
  on public.identity_verifications
  for select
  to authenticated
  using (public.este_administrator());

-- Update-ul e ingustat la coloanele deciziei prin trigger-ul de la punctul 5:
-- politica singura n-ar impiedica un admin sa rescrie scorul sau calea pozei.
drop policy if exists "admin: decide asupra verificarilor" on public.identity_verifications;
create policy "admin: decide asupra verificarilor"
  on public.identity_verifications
  for update
  to authenticated
  using (public.este_administrator())
  with check (public.este_administrator());

drop policy if exists "admin: vede profilurile" on public.profiles;
create policy "admin: vede profilurile"
  on public.profiles
  for select
  to authenticated
  using (public.este_administrator());

grant update on public.identity_verifications to authenticated;

-- -----------------------------------------------------------------------------
-- 5. Ce poate schimba un administrator intr-un caz
--
-- Doar decizia: status, reviewed_by, reviewed_at, notes. Dovezile pe care se
-- ia decizia — poze, CNP citit, scor, prag — raman cum le-a scris serviciul.
-- Altfel un raport de revizuire nu ar mai putea fi verificat de nimeni.
-- -----------------------------------------------------------------------------
create or replace function public.identity_verifications_protejeaza_dovezile()
returns trigger
language plpgsql
set search_path = ''
as $functie$
begin
  new.id                 := old.id;
  new.id_user            := old.id_user;
  new.buletin_image_path := old.buletin_image_path;
  new.selfie_image_path  := old.selfie_image_path;
  new.extracted_cnp      := old.extracted_cnp;
  new.similarity_score   := old.similarity_score;
  new.threshold_folosit  := old.threshold_folosit;
  new.creat_la           := old.creat_la;

  return new;
end;
$functie$;

drop trigger if exists identity_verifications_before_update on public.identity_verifications;
create trigger identity_verifications_before_update
  before update on public.identity_verifications
  for each row
  execute function public.identity_verifications_protejeaza_dovezile();

-- Decizia manuala trebuie sa se reflecte in profil, la fel ca cea automata.
-- Trigger-ul din 0004 prinde doar INSERT.
create or replace function public.sync_verification_status_update()
returns trigger
language plpgsql
security definer
set search_path = ''
as $functie$
begin
  if new.status is distinct from old.status then
    update public.profiles
       set verification_status = new.status,
           modificat_la = now()
     where id = new.id_user;
  end if;

  return new;
end;
$functie$;

drop trigger if exists identity_verifications_after_update on public.identity_verifications;
create trigger identity_verifications_after_update
  after update on public.identity_verifications
  for each row
  execute function public.sync_verification_status_update();

-- -----------------------------------------------------------------------------
-- 6. Pozele
--
-- Bucket-urile raman private. Administratorul primeste drept de citire, ca sa
-- se poata genera un URL semnat cu durata scurta; nimic nu devine public.
-- Politicile utilizatorilor pe propriile poze raman neatinse.
-- -----------------------------------------------------------------------------
drop policy if exists "buletine: adminul vede toate pozele" on storage.objects;
create policy "buletine: adminul vede toate pozele"
  on storage.objects for select to authenticated
  using (bucket_id = 'buletine' and public.este_administrator());

drop policy if exists "selfie: adminul vede toate pozele" on storage.objects;
create policy "selfie: adminul vede toate pozele"
  on storage.objects for select to authenticated
  using (bucket_id = 'selfie-uri' and public.este_administrator());

-- -----------------------------------------------------------------------------
-- 7. Urma
-- -----------------------------------------------------------------------------
create table if not exists public.acces_administrator (
  id               uuid primary key default gen_random_uuid(),
  id_administrator uuid not null references public.profiles (id) on delete cascade,
  id_utilizator    uuid references public.profiles (id) on delete set null,
  actiune          text not null,
  detalii          text,
  creat_la         timestamptz not null default now(),

  constraint acces_actiune_check check (actiune in (
    'lista_alerte', 'raport_pdf', 'raport_csv',
    'lista_verificari', 'vede_verificare', 'decide_verificare'
  ))
);

comment on table public.acces_administrator is
  'Cine s-a uitat la datele cui, si cand. Se adauga, nu se modifica si nu se sterge.';

create index if not exists acces_administrator_idx
  on public.acces_administrator (id_administrator, creat_la desc);
create index if not exists acces_utilizator_idx
  on public.acces_administrator (id_utilizator, creat_la desc);

alter table public.acces_administrator enable row level security;

-- Un administrator isi vede propria urma. Nu si pe a colegilor: cine verifica
-- verificatorii se uita in baza de date, nu prin aplicatie.
drop policy if exists "administrator: isi vede urma" on public.acces_administrator;
create policy "administrator: isi vede urma"
  on public.acces_administrator
  for select
  to authenticated
  using (id_administrator = (select auth.uid()) and public.este_administrator());

-- Fara update si fara delete: o urma care se poate rescrie nu mai e o urma.
drop policy if exists "administrator: isi scrie urma" on public.acces_administrator;
create policy "administrator: isi scrie urma"
  on public.acces_administrator
  for insert
  to authenticated
  with check (id_administrator = (select auth.uid()) and public.este_administrator());

grant select, insert on public.acces_administrator to authenticated;

-- -----------------------------------------------------------------------------
-- 8. Cum faci un administrator
--
--   insert into public.user_roles (user_id, role)
--   select id, 'admin' from auth.users where email = 'adresa@exemplu.ro';
--
-- -----------------------------------------------------------------------------
-- 9. Igiena tabelei user_roles — NU se ruleaza automat
--
-- Instructiunile de mai jos ar face tabela mai stricta, dar sterg si modifica
-- date. Nimic din aplicatie nu depinde de ele: se citeste doar daca exista un
-- rand cu role = 'admin', iar un duplicat sau un rol gol nu strica nimic.
--
-- Daca vrei sa le rulezi, uita-te intai la ce ai:
--
--   select * from public.user_roles order by user_id;
--
-- si abia apoi, cate una, verificand rezultatul:
--
--   -- randurile fara utilizator sau fara rol nu inseamna nimic
--   -- ATENTIE: sterge date. Uita-te la ele inainte.
--   -- delete from public.user_roles
--   --  where user_id is null or coalesce(btrim(role), '') = '';
--
--   -- acelasi om, acelasi rol, o singura data
--   -- create unique index user_roles_user_rol_uk
--   --   on public.user_roles (user_id, role);
--
--   -- doar rolurile pe care le cunoaste aplicatia
--   -- alter table public.user_roles
--   --   add constraint user_roles_role_check check (role in ('user', 'admin'));
--
--   -- un rand fara rol nu are sens; scoate default-ul gol
--   -- alter table public.user_roles alter column role drop default;
--   -- alter table public.user_roles alter column role set not null;
--   -- alter table public.user_roles alter column user_id set not null;
-- -----------------------------------------------------------------------------
